name = "cloudflare-worker"
main = "src/index.ts"
compatibility_date = "2024-05-25"

kv_namespaces = [
    { binding = "SESSION_KV", id = "317680158701488a9e3cf66f5446e81c" }
]

vars = { API_URL = "https://localhost:5000/" }

[env.production]
vars = { API_URL = "https://localhost:5000/" }

[env.staging]
vars = { API_URL = "https://localhost:5000/" }

[env.dev]
vars = { API_URL = "https://localhost:5000/" }
